name: Prettier

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened, synchronize]

permissions: write-all

jobs:
  prettier:
    if: "!contains(github.actor, 'win11bot')" # Skips if the bot triggered the event
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Run Commands
        run: |
          npx prettier --write .
          git config --global user.name "win11bot"
          git config --global user.email "w11bot@andrewstech.me"
          git add .
          git commit -m "Prettier (#${{ github.event.pull_request.number }})" -m "skip actions"
          git push
